### ISSUE TITLE
Mark add-ons which are premium

### ISSUE THREAD

**Issue by mitchelljkotler** [MuckRock/documentcloud#167]
Give a way to designate an add on requires AI credits, so we can filter on them and show appropriate UI changes (ask you to upgrade if you have a free account, show your AI credit balance, etc)

**Comment by duckduckgrayduck** [comment]
I checked all of the Add-Ons that are supposed to be marked as premium in categories, and made sure they are labelled. Anything else to do here?

**Comment by mitchelljkotler** [comment]
I think we might tweak the format of the credit cost as part of the redesign - I will leave this open until then
