### ISSUE TITLE
Solr timeout on query 

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/documentcloud#184]
See query here:
![image](https://github.com/MuckRock/documentcloud/assets/102841251/78b49b29-4d95-4e50-820a-15abd9909ff8)

**Comment by duckduckgrayduck** [comment]
Corresponding sentry error:
https://muckrock.sentry.io/issues/3456201632/?project=2689648&query=is%3Aunresolved&referrer=issue-stream&stream_index=1

**Comment by mitchelljkotler** [comment]
The issue is with stop words.  Changing the query to `"Covid in Custody"` or `Covid Custody` fixes the issue for now.  I have reached out to Inexture for help configuring stop words properly.
