### ISSUE TITLE
Block extraneous repos from appearing under Add-Ons list

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/documentcloud#191]
Users who aren't careful and setup the DocumentCloud github app give permissions to all of their repos. We should block these from being a part of the view on the backend, so I don't have to clean them up every once in a while. If they don't have specific files in the repo, they're probably not a valid Add-On and don't belong

**Comment by mitchelljkotler** [comment]
Gave a way to filter out bad ones instead of deleting them
