### ISSUE TITLE
Update `/projects` API to support improved front-end

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/documentcloud#192]
To support two user interactions in the front-end (https://github.com/MuckRock/documentcloud-frontend/issues/202), the `/projects` API needs to be updated:

1. The endpoint should support a `query` filter, like the `/addons` endpoint, that allows a user to search a list of projects.
2. Projects should have an optional boolean property called `pinned` that reflects whether it's pinned by the current user, similar to the `active` property of add-ons.
3. There should be a filter to return all projects a user has pinned and can view.

**Comment by allanlasser** [comment]
I've also noticed that when trying to send a patch to a project you don't own, a 403 is immediately returned. If we want to allow users to pin public  projects they don't own, we'll want to make sure this case is supported.

**Comment by mitchelljkotler** [comment]
This is now available on staging
