### ISSUE TITLE
Project privacy concerns

### ISSUE THREAD

**Issue by mitchelljkotler** [MuckRock/documentcloud#201]
* How to make projects publicly searchable without exposing projects that people thought were private
* Make sure people understand that existing projects are searchable and how to make them private
* All projects with only private documents should be made private
* How many organizations have more than 10 projects with some public documents
* Start capturing inbound links to projects

**Comment by mitchelljkotler** [comment]
- [ ] - Make private only projects private - MK
- [ ] - Track inbound links to projects - CA
- [ ] - How many organizations have more than 10 non-private projects - MK

**Comment by mitchelljkotler** [comment]
There are 686 users with more than 10 projects with at least one public document in them.  There are also a handful of users with a *lot* of projects with at least one public document in them:

```
{'user': 5675, 'c': 2094},
 {'user': 3007, 'c': 763},
 {'user': 10594, 'c': 443},
 {'user': 13174, 'c': 343},
 {'user': 352, 'c': 213},
 {'user': 1159, 'c': 165},
 {'user': 5131, 'c': 157},
 {'user': 12410, 'c': 150},
 {'user': 22354, 'c': 150},
 {'user': 100032, 'c': 149},
```

**Comment by mitchelljkotler** [comment]
There are 22,150 projects with no public documents in them which are currently public

**Comment by eyeseast** [comment]
Related: https://github.com/MuckRock/documentcloud-frontend/issues/268
