### ISSUE TITLE
Replace the current verification form

### ISSUE THREAD

**Issue by amandabee** [MuckRock/documentcloud#203]
We have a new (and hopefully clearer?) verification form: 

https://airtable.com/app93Yt5cwdVWTnqn/pagogIhgB1jZTzq00/form

We'd like to replace the old form (URL for that is https://airtable.com/app93Yt5cwdVWTnqn/shrZrgdmuOwW0ZLPM) with the new form.

**Comment by carruthm** [comment]
I'm still seeing the old form when using a test account. The request verification here is pointing to the old form. 
![Screenshot 2024-04-22 at 4 13 01 PM](https://github.com/MuckRock/documentcloud/assets/143415787/eb939edd-f1c3-41cf-8ed2-dfbe6bf4af45)

**Comment by amandabee** [comment]
The link appears twice on the page. There's the button, and then in the text itself it says "request verification here". The second link is still going to the old form.

**Comment by duckduckgrayduck** [comment]
It has been replaced in all language files, so this should be fixed. It should be live on the site in 15-20 min @carruthm @amandabee
