### ISSUE TITLE
Document pending endpoint

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud#206]
Related to https://github.com/MuckRock/documentcloud-frontend/issues/512

```json
[
  {
    "doc_id": 20000033,
    "images": 2,
    "texts": 2,
    "text_positions": 5,
    "pages": 11
  }
]
```

**Comment by mitchelljkotler** [comment]
https://www.notion.so/muckrock/Internal-APIs-62c43021ae9d4ff88d643ed7ecd22613
