### ISSUE TITLE
Newly created projects should be auto-pinned

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/documentcloud#229]
This is something I've seen come up in support tickets and is confusing for user experience. Newly created documents no longer automatically appear on the sidebar because they are not auto-pinned, thus you have to dig for that project in the "Browse" section which isn't a seamless project creation experience

**Comment by mitchelljkotler** [comment]
The backend now pins projects by default, but you need to refresh to get it into the pinned list - the frontend should automatically refresh the pin list upon project creation
