### ISSUE TITLE
Inconsistent user permissions when viewing documents

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud#233]
Users who should have edit access to documents are sometimes unable to use any document actions other than adding private notes. This can occur with users viewing documents they own and contributed, as well as with MR admins troubleshooting or redacting private or public documents. 

From an admin perspective, it's frustrating when a task that should take 10 seconds ends up diverting me for twenty minutes or more. More importantly, [this bug has impacted users working on deadline items.](https://muckrock.zendesk.com/agent/tickets/129840)

As far as I can tell, if this error is occurring, it occurs across all documents for that user. Once it happens, I haven't found a way to get things working again. I've tried refreshing multiple times, clearing my cache and cookies, hijacking other users, viewing the document in an incognito tab, and refreshing/hijacking in an incognito tab. It seems to just resolve itself after a while. 

This makes me wonder if it's token/time based, but I don't know for sure. Chris mentioned it might have something to do with old accounts.

I'm not sure how to reproduce this bug. It seems to happen to me randomly, maybe once or twice a month. I've had it occur both when accessing DocumentCloud independently from the browser and when redirected to DocumentCloud through a link on MR.

**Comment by eyeseast** [comment]
Haven't figured out how to reproduce it. If anyone encounters this, please check:
- the console, for errors
- the API, for `edit_access` permissions
- the current user's active organization

**Comment by duckduckgrayduck** [comment]
We figured this out I think during our call- Adrien was trying to edit a collection of documents- some of which Adrien wasn't a part of.
