### ISSUE TITLE
When a user creates a new organization on Squarelet, their active organization should change on DocumentCloud. 

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/documentcloud#239]
This eases on-boarding process for user's that sign up for a new account -> create a new org -> request verification.

**Comment by duckduckgrayduck** [comment]
The logic for creating a new org on Squarelet is here:
https://github.com/MuckRock/squarelet/blob/68b6c24a2dc528278b9f2ae5477b7361f6b17613/squarelet/organizations/views.py#L206

The logic for setting an org as your active org on DocumentCloud front end is here:
https://github.com/MuckRock/documentcloud-frontend/blob/46dc2232a9043bd1d7154ae1063bcd3977557e2f/src/pages/app/accounts/OrgPicker.svelte#L41

The API call made on the front-end is here:
https://github.com/MuckRock/documentcloud-frontend/blob/master/src/api/orgAndUser.ts#L29

How do I call this when a new org is created on Squarelet? (or maybe just first login?)

**Comment by duckduckgrayduck** [comment]
On squarelet-auth, setting a user's active organization is here:
https://github.com/MuckRock/squarelet-auth/blob/d3c1892c0635e16daeddf25c3bbbf0363b1748a1/squarelet_auth/users/models.py#L133

**Comment by duckduckgrayduck** [comment]
So Mitch and I are investigating this issue and this should be the current behavior:
https://github.com/MuckRock/squarelet-auth/blob/d3c1892c0635e16daeddf25c3bbbf0363b1748a1/squarelet_auth/users/utils.py#L104

If a user creates a new account, creates a new org, and then signs into DocumentCloud for the first time, the correct newly created org is marked as active. If we can get someone to replicate this issue, then we might be able to discover where this is a problem. 

I have a video recording of the current behavior, which seems to be correct: 
https://drive.google.com/file/d/1fptPwH8FlAG_vRgRDSC_MDEEd1eSk_ch/view?usp=sharing

Mitch will try ordering the organizations (putting individual orgs last) when they get updated here:
https://github.com/MuckRock/squarelet-auth/blob/d3c1892c0635e16daeddf25c3bbbf0363b1748a1/squarelet_auth/users/utils.py#L104

to see if it will help with this behavior we can't seem to replicate

**Comment by mitchelljkotler** [comment]
There seemed to be the possibility of the wrong org being activated if they created the org before signing in to DocumentCloud for the first time - the result was not deterministic, even though we couldn't replicate the incorrect behavior.  I now sort the orgs, so individual orgs are always last.  I also added logging, so if it does happen again, we should be able to get some insight.
