### ISSUE TITLE
Support/Improved Error Handling for PDF Portfolios

### ISSUE THREAD

**Issue by morisy** [MuckRock/documentcloud#55]
Adobe has a PDF-like format called PDF portfolios that pretend to be PDFs but are not, instead displaying this garbage when opened or loaded into DocumentCloud:

<img width="1164" alt="Screen Shot 2020-03-09 at 10 21 07 PM" src="https://user-images.githubusercontent.com/136939/76273458-486b7c00-6254-11ea-992c-5d89af38f921.png">

I'm not aware of any good open source tools for de-compiling these into something that's actually parsable, but maybe as a starting point we could add some handling that warns people these are a PDF Portfolio with some best practices for handling.

Pretty low priority.

Example for reference: https://cdn.muckrock.com/foia_files/2019/09/04/RESPONSIVE20EMAILS.pdf

**Comment by duckduckgrayduck** [comment]
duplicate
